SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS `subscriptions` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `gym_id` int(11) NOT NULL,
  `member_id` int(11) NOT NULL,
  `membership_plan_id` int(11) NOT NULL,
  `start_date` date NOT NULL,
  `end_date` date NOT NULL,
  `status` enum('active','expired','frozen','cancelled') NOT NULL DEFAULT 'active',
  `price_snapshot` decimal(12,2) NOT NULL,
  `currency_snapshot` enum('USD','LBP') NOT NULL,
  `notes` text DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `renewed_at` timestamp NULL DEFAULT NULL,
  `frozen_at` timestamp NULL DEFAULT NULL,
  `cancelled_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_subscriptions_gym_status_dates` (`gym_id`,`status`,`end_date`,`start_date`),
  KEY `idx_subscriptions_gym_member` (`gym_id`,`member_id`,`end_date`),
  KEY `idx_subscriptions_gym_plan` (`gym_id`,`membership_plan_id`),
  KEY `idx_subscriptions_member` (`member_id`),
  KEY `idx_subscriptions_plan` (`membership_plan_id`),
  KEY `idx_subscriptions_created_by` (`created_by`),
  KEY `idx_subscriptions_updated_by` (`updated_by`),
  CONSTRAINT `fk_subscriptions_gym` FOREIGN KEY (`gym_id`) REFERENCES `gyms` (`id`) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT `fk_subscriptions_member` FOREIGN KEY (`member_id`) REFERENCES `members` (`id`) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT `fk_subscriptions_plan` FOREIGN KEY (`membership_plan_id`) REFERENCES `membership_plans` (`id`) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT `fk_subscriptions_created_by` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT `fk_subscriptions_updated_by` FOREIGN KEY (`updated_by`) REFERENCES `users` (`id`) ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT `chk_subscriptions_dates` CHECK (`end_date` >= `start_date`),
  CONSTRAINT `chk_subscriptions_price_snapshot` CHECK (`price_snapshot` >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
